/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOrganizationRouteImport } from './routes/app/organization'
import { Route as AppMembersRouteImport } from './routes/app/members'
import { Route as AppArchiveRouteImport } from './routes/app/archive'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOrganizationRouteImport } from './routes/(auth)/organization'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authInvitationRouteImport } from './routes/(auth)/invitation'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app/projects/$projectId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app/customers/$customerId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOrganizationRoute = authOrganizationRouteImport.update({
  id: '/(auth)/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authInvitationRoute = authInvitationRouteImport.update({
  id: '/(auth)/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/invitation': typeof authInvitationRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRoute
  '/organization': typeof authOrganizationRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/members': typeof AppMembersRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitation': typeof authInvitationRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRoute
  '/organization': typeof authOrganizationRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/members': typeof AppMembersRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/invitation': typeof authInvitationRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/onboarding': typeof authOnboardingRoute
  '/(auth)/organization': typeof authOrganizationRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/members': typeof AppMembersRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/organization'
    | '/reset-password'
    | '/signup'
    | '/app/archive'
    | '/app/members'
    | '/app/organization'
    | '/app/'
    | '/api/auth/$'
    | '/app/customers/$customerId'
    | '/app/projects/$projectId'
    | '/app/customers/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/organization'
    | '/reset-password'
    | '/signup'
    | '/app/archive'
    | '/app/members'
    | '/app/organization'
    | '/app'
    | '/api/auth/$'
    | '/app/customers/$customerId'
    | '/app/projects/$projectId'
    | '/app/customers'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/(auth)/invitation'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/(auth)/organization'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/app/archive'
    | '/app/members'
    | '/app/organization'
    | '/app/'
    | '/api/auth/$'
    | '/app/customers/$customerId'
    | '/app/projects/$projectId'
    | '/app/customers/'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authInvitationRoute: typeof authInvitationRoute
  authLoginRoute: typeof authLoginRoute
  authOnboardingRoute: typeof authOnboardingRoute
  authOrganizationRoute: typeof authOrganizationRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/archive': {
      id: '/app/archive'
      path: '/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/organization': {
      id: '/(auth)/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof authOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/invitation': {
      id: '/(auth)/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof authInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppMembersRoute: typeof AppMembersRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppMembersRoute: AppMembersRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authInvitationRoute: authInvitationRoute,
  authLoginRoute: authLoginRoute,
  authOnboardingRoute: authOnboardingRoute,
  authOrganizationRoute: authOrganizationRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
